version: '3.8'

services:
  db:
    image: postgres:15
    container_name: api-clientes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Erfon@12345
      POSTGRES_DB: neoapp-desafio
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: